server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://127.0.0.1:8762/eureka
    enabled: true

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SDSACT/microservices-coe-configurations.git
#          username:
#          password:

