server:
  port: ${PORT:7071}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://cesutil/config/config-repo}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://10.71.171.22}:${EUREKA_SERVER_PORT:7075}/eureka/
    enabled: true
---
spring:
  profiles: stage-config1
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://cesutil/config/config-repo}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA1_SERVER_URL:http://10.71.172.22}:${EUREKA1_SERVER_PORT:7075}/eureka/,${EUREKA2_SERVER_URL:http://10.71.174.22}:${EUREKA2_SERVER_PORT:7075}/eureka/
---
spring:
  profiles: stage-config2
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://cesutil/config/config-repo}
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA1_SERVER_URL:http://10.71.174.22}:${EUREKA1_SERVER_PORT:7075}/eureka/,${EUREKA2_SERVER_URL:http://10.71.172.22}:${EUREKA2_SERVER_PORT:7075}/eureka/
---
