server:
  port: 7072
spring:
  profiles:
    active: config1

--

spring:
  profiles: config1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SDSACT/microservices-coe-configurations.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.71.172.22:7071/eureka/,http://10.71.174.22:7071/eureka/
    enabled: true
    
---

spring:
  profiles: config2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SDSACT/microservices-coe-configurations.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.71.174.22:7071/eureka/,http://10.71.172.22:7071/eureka/
    enabled: true
