server:
  port: ${PORT:8888}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://config-repo}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
    enabled: true
---
spring:
  profiles: stage-config1
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://config-repo}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA1_SERVER_URL:stage-eureka1}:${EUREKA1_SERVER_PORT:8761}/eureka/,${EUREKA2_SERVER_URL:stage-eureka2}:${EUREKA2_SERVER_PORT:8761}/eureka/
---
spring:
  profiles: stage-config2
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://config-repo}
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA1_SERVER_URL:stage-eureka2}:${EUREKA1_SERVER_PORT:8761}/eureka/,${EUREKA2_SERVER_URL:stage-eureka1}:${EUREKA2_SERVER_PORT:8761}/eureka/
---