server:
  port: ${PORT:7072}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:https://github.com/SDSACT/microservices-coe-configurations.git}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://10.71.174.22}:${EUREKA_SERVER_PORT:7071}/eureka/
    enabled: true
---
spring:
  profiles: stage-config1
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:https://github.com/SDSACT/microservices-coe-configurations.git}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA1_SERVER_URL:http://10.71.172.22}:${EUREKA1_SERVER_PORT:7071}/eureka/,${EUREKA2_SERVER_URL:http://10.71.174.22}:${EUREKA2_SERVER_PORT:7071}/eureka/
---
spring:
  profiles: stage-config2
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:https://github.com/SDSACT/microservices-coe-configurations.git}
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA1_SERVER_URL:http://10.71.174.22}:${EUREKA1_SERVER_PORT:7071}/eureka/,${EUREKA2_SERVER_URL:http://10.71.172.22}:${EUREKA2_SERVER_PORT:7071}/eureka/
---